#!/bin/bash

timestamp=`date +%Y-%m-%d_%H%M%S`

o=output
r=$o/raw
mkdir -p $r

rawFile=$r/FL-$timestamp.csv

echo "Downloading COVID-19 data at $timestamp"
python download-covid19-data.py $rawFile
ret=$?

if [[ $ret -eq 1 ]]; then
	echo "Exiting program"
	exit
fi

echo "Making data files for charts."
Rscript make-datafiles-for-charts.r $rawFile $o

echo "Updating charts"
Rscript update-charts.r $timestamp "output/datawrapper/county.csv" "output/datawrapper/south-fl.csv"
