#!/bin/bash

timestamp=`date +%Y-%m-%d_%H%M%S`

o=output
r=$o/raw
mkdir -p $r

rawFile=$r/FL-$timestamp.csv

echo "Downloading COVID-19 data."
python download-covid19-data.py $rawFile

echo "Making data files for charts."
Rscript make-datafiles-for-charts.r $rawFile $o

echo "Updating charts"
Rscript update-charts.r $timestamp